/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/kennisartikelen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all Kennisartikelen */
        get: operations["getKennisartikelen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vac": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all VAC */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of VAC */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VAC"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Kennisartikel */
        Kennisartikel: {
            /**
             * URL
             * Format: uri
             * @description De unieke URL van dit object binnen deze API.
             */
            url: string;
            /**
             * UUID
             * Format: uuid
             * @description De identificatie die binnen deze API gebruikt wordt voor de resource.
             */
            uuid: string;
            /**
             * UPN URI
             * Format: uri
             * @description De UPN URI van het specifieke product.
             */
            upnUri: string;
            /**
             * Publicatiedatum
             * Format: date
             * @description De datum die aangeeft wanneer het product gepubliceerd is/wordt.
             */
            publicatieDatum: string | null;
            /**
             * Product Aanwezig
             * @description Een boolean die aangeeft of de organisatie dit product levert of niet.
             */
            productAanwezig: boolean | null;
            /**
             * Product Valt Onder
             * @description Als een product valt onder een ander product, dan staat deze hier vermeld.
             */
            productValtOnder?: string | null;
            /**
             * De Leverende Organisatie
             * @description De organisatie die dit product levert en de teksten hiervan beheert.
             */
            verantwoordelijkeOrganisatie: {
                /**
                 * URL van object
                 * Format: uri
                 * @description De unieke URL van dit object binnen deze API.
                 */
                url: string;
                /**
                 * OWMS Identifier
                 * Format: uri
                 * @description De OWMS Identifier van de hoofdorganisatie van deze lokale overheid.
                 */
                owmsIdentifier: string;
                /**
                 * OWMS label
                 * @description OWMS label van de hoofdorganisatie van deze lokale overheid.
                 */
                owmsPrefLabel?: string;
                /**
                 * Einddatum
                 * Format: date-time
                 * @description De einddatum, zoals gevonden in het OWMS-model.
                 */
                owmsEndDate: string;
            };
            /**
             * Locaties waar Beschikbaar
             * @description Een lijst met locaties waarop dit product beschikbaar is. Deze is nog niet nodig voor KISS en mag null zijn.
             */
            locaties: string[] | null;
            /**
             * Doelgroep
             * @description De doelgroep van dit product.
             * @enum {string}
             */
            doelgroep: "eu-burger" | "eu-bedrijf";
            /**
             * Afdeling of Afdelingen
             * @description De afdeling of afdelingen die de teksten van dit product beheert.
             */
            afdelingen?: {
                /**
                 * Identifier Afdeling
                 * @description De unieke identifier van de afdeling.
                 */
                afdelingId?: string;
                /**
                 * Naam Afdeling
                 * @description De naam van de afdeling.
                 */
                afdelingnaam: string;
            }[];
            /**
             * Vertalingen
             * @description Een lijst met specifieke teksten op basis van taal.
             */
            vertalingen: {
                /**
                 * Weergavetaal
                 * @description De taal waarin het kennisartikel is geschreven.
                 * @enum {string}
                 */
                taal: "nl" | "en";
                /**
                 * Titel van het Kennisartikel
                 * @description Een korte herkenbare titel van het kennisartikel.
                 */
                titel?: string;
                /**
                 * Inleiding
                 * @description Inleidende tekst voor het product.
                 */
                tekst?: string;
                /**
                 * Aanvraag
                 * @description De beschrijving van hoe het product wordt aangevraagd. Aanpak.
                 */
                procedureBeschrijving?: string;
                /**
                 * Bewijs
                 * @description Dit bevat de bewijsstukken die de burger of ondernemer nodig heeft om dit product aan te vragen.
                 */
                bewijs?: string;
                /**
                 * Voorwaarden
                 * @description Dit zijn de voorwaarden voor het aanvragen van het product.
                 */
                vereisten?: string;
                /**
                 * Bezwaar
                 * @description Beschrijft hoe de burger of ondernemer bezwaar kan maken tegen een besluit over dit product.
                 */
                bezwaarEnBeroep?: string;
                /**
                 * Kosten
                 * @description Beschrijft hoe de burger of ondernemer kan betalen en wat de kosten zijn.
                 */
                kostenEnBetaalmethoden?: string;
                /**
                 * Termijn
                 * @description Informatie over de termijn voor het aanvragen van dit product.
                 */
                uitersteTermijn?: string;
                /**
                 * Wat te doen bij Geen Reactie
                 * @description Beschrijft wat de aanvrager moet doen bij geen reactie.
                 */
                wtdBijGeenReactie?: string;
                /**
                 * Bijzonderheden
                 * @description Bijzonderheden rondom het product die nog niet is vermeld bij één van de andere onderdelen.
                 */
                notice?: string;
                /**
                 * Contact
                 * @description Beschrijving van hoe en waar de burger of ondernemer contact op kan nemen over dit product.
                 */
                contact?: string;
                /**
                 * Interne Informatie
                 * @description Interne informatie, alleen bestemd voor de Balie- of KCC-medewerker.
                 */
                deskMemo?: string;
                /**
                 * Trefwoorden
                 * @description Trefwoorden die passen bij het Kennisartikel/product.
                 */
                trefwoorden?: {
                    /**
                     * Trefwoord
                     * @description Een trefwoord.
                     */
                    trefwoord: string;
                }[];
                /**
                 * Datum Laatste Wijziging
                 * Format: date-time
                 * @description Datum wanneer dit product voor het laatst is gewijzigd.
                 */
                datumWijziging: string;
            }[];
            /**
             * Beschikbare Talen
             * @description Alle beschikbare talen.
             */
            beschikbareTalen: string[];
        };
        /** VAC */
        VAC: {
            /** @description De vraag waar de VAC antwoord op geeft. */
            vraag: string;
            /**
             * @description De actuele status van de VAC.
             * @enum {string}
             */
            status: "actief" | "non-actief" | "te-verwijderen";
            /** @description Het antwoord op de bij 'vraag' gestelde vraag. */
            antwoord: string;
            /**
             * @description De doelgroep van de VAC.
             * @enum {string}
             */
            doelgroep: "eu-burger" | "eu-bedrijf" | "eu-burger-bedrijf";
            /**
             * Gerelateerde Afdelingen
             * @description Afdelingen aan wie de VAC gerelateerd is.
             */
            afdelingen?: {
                /** @description De unieke identifier van de afdeling. */
                afdelingId: string;
                /** @description De naam van de afdeling. */
                afdelingNaam: string;
            }[];
            /** @description Een toelichting bij de VAC ten behoeve van de medewerker van het contactcentrum. */
            toelichting?: string;
            /**
             * Trefwoorden
             * @description Trefwoorden die passen bij de VAC.
             */
            trefwoorden?: {
                /** @description Een trefwoord. */
                trefwoord: string;
            }[];
            /**
             * Gerelateerde VACs
             * @description VACs die gerelateerd zijn aan de VAC.
             */
            gerelateerdeVACs?: {
                /**
                 * Format: uri
                 * @description De URI van de gerelateerde VAC.
                 */
                VAC: string;
            }[];
            /**
             * Gerelateerde Producten
             * @description Producten die gerelateerd zijn aan de VAC.
             */
            gerelateerdeProducten?: {
                /**
                 * Format: uri
                 * @description De URI van het gerelateerde product.
                 */
                product: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getKennisartikelen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of Kennisartikelen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kennisartikel"][];
                };
            };
        };
    };
}
