openapi: 3.0.3
info:
  title: CSV Import API
  description: API for importing a CSV file containing vraag, antwoord, and doelgroep.
  version: 1.0.0
servers:
  - url: "http://localhost:4002/api/v1/import"
    description: Local development server
paths:
  /import:
    post:
      summary: Import CSV File
      description: Uploads a CSV file and returns a JSON representation.
      operationId: importCSV
      security:
        - TokenAuth: []
      parameters:
        - name: locale
          in: query
          required: true
          description: The locale of the data.
          schema:
            type: string
            enum: [nl]
            example: "nl"
        - name: type
          in: query
          required: true
          description: The type of import.
          schema:
            type: string
            enum: [vac]
            example: "vac"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload.
      responses:
        "200":
          description: Successful import.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "CSV converted to JSON"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ImportedRecord"
        "400":
          description: Bad Request (e.g., invalid file format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format. Please upload a CSV file."
        "401":
          description: Unauthorized (Missing or invalid API token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized. Provide a valid API token."
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An error occurred while processing the file."

components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >
        API token authentication. Use either:
        - `Token ************`
        - `**************` (without "Token" prefix)

  schemas:
    ImportedRecord:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: "95f27d6c-b0b5-40fd-98fc-70a093712efc"
        type:
          type: string
          example: "http://localhost:4001/api/v2/objecttypes/vac"
        url:
          type: string
          format: uri
          example: "http://localhost:4001/api/v2/objects/95f27d6c-b0b5-40fd-98fc-70a093712efc"
        record:
          type: object
          properties:
            index:
              type: integer
              example: 93
            startAt:
              type: string
              format: date-time
              example: "2025-03-07T10:01:57.596Z"
            typeVersion:
              type: integer
              example: 1
            data:
              type: object
              properties:
                uuid:
                  type: string
                  format: uuid
                  example: "95f27d6c-b0b5-40fd-98fc-70a093712efc"
                vraag:
                  type: string
                  example: "How does this API work?"
                antwoord:
                  type: string
                  example: "<h2>This API converts a CSV file to JSON when you provide the required fields.</h2> The required fields are: <ul><li>A CSV file for VAC that includes `vraag` and `antwoord` columns</li><li>API parameters: locale: 'nl' and type: 'vac'</li><li>A valid Strapi API Token</li></ul>"
                status:
                  type: string
                  nullable: true
                  example: null
                doelgroep:
                  type: string
                  example: "eu-burger"
                afdelingen:
                  type: array
                  items:
                    type: string
                  example: []
                toelichting:
                  type: string
                  nullable: true
                  example: null
                trefwoorden:
                  type: array
                  items:
                    type: string
                  example: []
                url:
                  type: string
                  format: uri
                  example: "http://localhost:4001/api/v2/objects/95f27d6c-b0b5-40fd-98fc-70a093712efc"
            geometry:
              type: object
              nullable: true
              example: null
            endAt:
              type: string
              format: date-time
              nullable: true
              example: null
            registrationAt:
              type: string
              format: date-time
              example: "2025-03-07T10:01:57.596Z"
