version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "npm"
    directory: "/"
    # Only have Dependabot to create pull requests for these dependencies
    # to prevent using up Chromatic screenshots
    allow:
      - dependency-name: "@gemeente-rotterdam/*"
      - dependency-name: "@gemeente-denhaag/*"
      - dependency-name: "@utrecht/*"
      - dependency-name: "@nl-design-system/*"
      - dependency-name: "@nl-design-system-unstable/*"
    # Bundle the above dependencies into a single pull request
    groups:
      allowed-deps:
        patterns:
          - "@gemeente-rotterdam/*"
          - "@gemeente-utrecht/*"
          - "@utrecht/*"
          - "@nl-design-system/*"
          - "@nl-design-system-unstable/*"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
