version: "3.1"

services:
  strapi:
    build:
      args:
        NODE_ENV: development
        STRAPI_HOSTNAME: localhost
      context: .
      dockerfile: ./Dockerfile
    command: "dev:strapi"
    ports:
      - 1337:1337
    volumes:
      - .:/var/www/
      # - /var/www/node_modules
      # - /var/www/apps/frontend/node_modules
      # - /var/www/packages/strapi-dashboard/node_modules
    networks:
      - api
      - private
    environment:
      - STRAPI_HOSTNAME=localhost
      - STRAPI_FRONTEND_URL=https://utrecht-strapi-website.frameless.io/
  website:
    build:
      args:
        NODE_ENV: development
        STRAPI_HOSTNAME: localhost
      context: .
      dockerfile: ./Dockerfile
    # command: "dev:website"
    ports:
      - 1234:1234
    volumes:
      - .:/var/www/
      # - /var/www/node_modules
      # - /var/www/apps/frontend/node_modules
      # - /var/www/packages/strapi-dashboard/node_modules
    networks:
      - api
      - public
    environment:
      - REVALIDATE_SECRET_TOKEN=9ABCD68B-8B89-46EA-AAC6-BCE97BCB900A
      - STRAPI_BACKEND_URL=http://localhost:1337/graphql
      - STRAPI_FRONTEND_URL=https://utrecht-strapi-website.frameless.io/
      - STRAPI_HOSTNAME=localhost
      - POSTGRES_DB=exampledb
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepass
    # volumes:
    #   - strapi:/var/www/html

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=exampledb
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepass
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - private
    ports:
      - 5432:5432

volumes:
  db:

networks:
  api:
  public:
  private:
