version: "3.8"
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    volumes:
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./apps/strapi-dashboard/config:/opt/app/apps/strapi-dashboard/config
      - ./apps/strapi-dashboard/src:/opt/app/apps/strapi-dashboard/src
      - ./apps/strapi-dashboard/package.json:/opt/app/apps/strapi-dashboard/package.json
      - ./apps/strapi-dashboard/public/uploads:/opt/app/apps/strapi-dashboard/public/uploads
    command: npm run --workspace @frameless/strapi-dashboard start
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      STRAPI_FRONTEND_URL: ${STRAPI_FRONTEND_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapi_db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_SIGNED_URL_EXPIRES: ${AWS_SIGNED_URL_EXPIRES}
      AWS_BUCKET: ${AWS_BUCKET}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi_network
    depends_on:
      - strapi_db
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ./bin/wait-for-it.sh strapi:1337 -- npm run --workspace @frameless/frontend start
    environment:
      REVALIDATE_SECRET_TOKEN: ${REVALIDATE_SECRET_TOKEN}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      STRAPI_UPLOAD_PROVIDER_HOSTNAME: ${STRAPI_UPLOAD_PROVIDER_HOSTNAME}
      STRAPI_FRONTEND_URL: ${STRAPI_FRONTEND_URL}
      STRAPI_BACKEND_URL: ${STRAPI_BACKEND_URL}
    ports:
      - "3000:3000"
    networks:
      - strapi_network
    depends_on:
      - strapi
      - strapi_db
  strapi_db:
    container_name: strapi_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9000:80"
    networks:
      - strapi_network
    depends_on:
      - strapi_db
volumes:
  strapi-data:

networks:
  strapi_network:
    name: Strapi network
    driver: bridge
