
FROM node:20-alpine as build
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache libc6-compat build-base bash gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
ARG STRAPI_PUBLIC_URL
ENV STRAPI_PUBLIC_URL=${STRAPI_PUBLIC_URL}
WORKDIR /opt/app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
COPY ./package.json ./pnpm-lock.yaml ./
RUN npm install -g pnpm@8

COPY ./apps/pdc-dashboard/package.json apps/pdc-dashboard/package.json
COPY ./apps/pdc-frontend/package.json apps/pdc-frontend/package.json
COPY ./apps/pdc-sc/package.json apps/pdc-sc/package.json
COPY ./apps/vth-dashboard/package.json apps/vth-dashboard/package.json
COPY ./apps/vth-frontend/package.json apps/vth-frontend/package.json
COPY ./apps/kennisbank-dashboard/package.json apps/kennisbank-dashboard/package.json
COPY ./apps/kennisbank-frontend/package.json apps/kennisbank-frontend/package.json
COPY ./packages/catalogi-data/package.json packages/catalogi-data/package.json
COPY ./packages/preview-button/package.json packages/preview-button/package.json
COPY ./packages/samenwerkende-catalogi/package.json packages/samenwerkende-catalogi/package.json
COPY ./packages/strapi-plugin-gemeente-select/package.json packages/strapi-plugin-gemeente-select/package.json
COPY ./packages/strapi-plugin-scheme-select/package.json packages/strapi-plugin-scheme-select/package.json
COPY ./packages/strapi-tiptap-editor/package.json packages/strapi-tiptap-editor/package.json
COPY ./packages/ui/package.json packages/ui/package.json
COPY ./packages/upl/package.json packages/upl/package.json
COPY ./packages/strapi-plugin-uniform-product-name/package.json packages/strapi-plugin-uniform-product-name/package.json


# Build target dependencies #
#############################
FROM build AS dependencies
# Install prod dependencies
RUN pnpm -g add patch-package node-gyp
COPY ./patches /opt/app/patches
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

# Build target builder #
########################
FROM build AS builder
COPY --from=dependencies /opt/app/node_modules /opt/app/node_modules
COPY . /opt/app/
RUN  pnpm  --filter @frameless/upl run build && \
    pnpm  --filter @frameless/strapi-plugin-uniform-product-name run build && \
    pnpm  --filter @frameless/strapi-tiptap-editor run build && \
    pnpm  --filter @frameless/ui run build && \
    pnpm  --filter @frameless/catalogi-data run build && \
    pnpm  --filter @frameless/samenwerkende-catalogi run build && \
    pnpm  --filter @frameless/pdc-sc run build

# Build target production #
###########################
FROM build AS development
COPY --from=builder /opt/app /opt/app
COPY --from=dependencies /opt/app/node_modules /opt/app/node_modules
RUN chmod +x ./bin/wait-for-it.sh
EXPOSE 1337
CMD ["pnpm", "dev"]
