version: "3.8"
services:
  pdc_strapi:
    container_name: pdc_strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: strapi:latest
    restart: unless-stopped
    volumes:
      - ./apps/pdc-dashboard/public/uploads:/opt/app/apps/pdc-dashboard/public/uploads
    command: npm run start:pdc-dashboard
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: pdc_strapi_db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - pdc_strapi_network
    depends_on:
      - pdc_strapi_db
  pdc_frontend:
    container_name: pdc_frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: ./bin/wait-for-it.sh pdc_strapi:1337 -- npm run start:pdc-frontend
    environment:
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      STRAPI_PRIVATE_URL: ${STRAPI_PRIVATE_URL}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      STRAPI_PUBLIC_URL: ${STRAPI_PUBLIC_URL}
    ports:
      - "3000:3000"
    networks:
      - pdc_strapi_network
    depends_on:
      - pdc_strapi
      - pdc_strapi_db
  pdc_strapi_db:
    container_name: pdc_strapi_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - pdc-strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - pdc_strapi_network
  pdc_pgadmin:
    container_name: pdc_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9000:80"
    networks:
      - pdc_strapi_network
    depends_on:
      - pdc_strapi_db
volumes:
  pdc-strapi-data:

networks:
  pdc_strapi_network:
    name: Strapi network
    driver: bridge
