version: "3"
services:
  kennisbank_strapi:
    container_name: kennisbank_strapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: strapi:latest
    restart: unless-stopped
    volumes:
      - ./package.json:/opt/app/package.json
      - ./pnpm-lock.yaml:/opt/app/pnpm-lock.yaml
      - ./apps/kennisbank-dashboard/config:/opt/app/apps/kennisbank-dashboard/config
      - ./apps/kennisbank-dashboard/src:/opt/app/apps/kennisbank-dashboard/src
      - ./apps/kennisbank-dashboard/package.json:/opt/app/apps/kennisbank-dashboard/package.json
      - ./apps/kennisbank-dashboard/public/:/opt/app/apps/kennisbank-dashboard/public/
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        pnpm --filter @frameless/kennisbank-dashboard run dev
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: kennisbank_strapi_db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - kennisbank_strapi_network
    depends_on:
      - kennisbank_strapi_db
  kennisbank_frontend:
    container_name: kennisbank_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: ./bin/wait-for-it.sh -s kennisbank_strapi:1337 -t 25 -- pnpm --filter @frameless/kennisbank-frontend run dev
    environment:
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      STRAPI_PRIVATE_URL: ${STRAPI_PRIVATE_URL}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      STRAPI_PUBLIC_URL: ${STRAPI_PUBLIC_URL}
    volumes: # enable hot-reload
      - ./apps/kennisbank-frontend/src:/opt/app/apps/kennisbank-frontend/src
      - ./apps/kennisbank-frontend/public:/opt/app/apps/kennisbank-frontend/public
      - ./apps/kennisbank-frontend/.next:/opt/app/apps/kennisbank-frontend/.next
      - ./apps/kennisbank-frontend/package.json:/opt/app/apps/kennisbank-frontend/package.json
    ports:
      - "3000:3000"
    networks:
      - kennisbank_strapi_network
    depends_on:
      - kennisbank_strapi
      - kennisbank_strapi_db
  kennisbank_strapi_db:
    container_name: kennisbank_strapi_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - kennisbank-strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - kennisbank_strapi_network
  kennisbank_pgadmin:
    container_name: kennisbank_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - kennisbank_strapi_network
    depends_on:
      - kennisbank_strapi_db

volumes:
  kennisbank-strapi-data:

networks:
  kennisbank_strapi_network:
    name: Strapi network
    driver: bridge
