version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: strapi:latest
    restart: unless-stopped
    command: npm run --workspace apps/strapi-dashboard dev
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapi_db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapi_db
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: npm run --workspace apps/frontend dev
    env_file: .env
    environment:
      REVALIDATE_SECRET_TOKEN: ${REVALIDATE_SECRET_TOKEN}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      STRAPI_HOSTNAME: ${STRAPI_HOSTNAME}
      STRAPI_FRONTEND_URL: ${STRAPI_FRONTEND_URL}
      STRAPI_BACKEND_URL: ${STRAPI_BACKEND_URL}
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - strapi
      - strapi_db
  strapi_db:
    container_name: strapi_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - strapi
    depends_on:
      - strapi_db

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
