version: "3.8"

services:
  vth_strapi:
    container_name: vth_strapi
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
        STRAPI_PUBLIC_URL: ${STRAPI_PUBLIC_URL}
    image: vth-strapi-dev:latest
    restart: unless-stopped
    volumes:
      - ./apps/vth-dashboard/src:/app/apps/vth-dashboard/src
      - ./apps/vth-dashboard/config:/app/apps/vth-dashboard/config
      - ./apps/vth-dashboard/public:/app/apps/vth-dashboard/public
      - ./apps/vth-dashboard/dist:/app/apps/vth-dashboard/dist
      - ./apps/vth-dashboard/.strapi:/app/apps/vth-dashboard/.strapi
      - ./apps/vth-dashboard/.cache:/app/apps/vth-dashboard/.cache
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: vth_strapi_db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      STRAPI_ENV_LABEL: ${STRAPI_ENV_LABEL}
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      - vth_network
    depends_on:
      vth_strapi_db:
        condition: service_healthy
    command: pnpm --filter @frameless/vth-dashboard dev

  vth_frontend:
    container_name: vth_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    image: vth-frontend-dev:latest
    restart: unless-stopped
    volumes:
      - ./apps/vth-frontend/src:/app/apps/vth-frontend/src
      - ./apps/vth-frontend/public:/app/apps/vth-frontend/public
      - ./apps/vth-frontend/.next:/app/apps/vth-frontend/.next
    environment:
      PREVIEW_SECRET_TOKEN: ${PREVIEW_SECRET_TOKEN}
      STRAPI_PRIVATE_URL: ${STRAPI_PRIVATE_URL}
      FRONTEND_PUBLIC_URL: ${FRONTEND_PUBLIC_URL}
      STRAPI_PUBLIC_URL: ${STRAPI_PUBLIC_URL}
      NODE_ENV: development
    ports:
      - "3000:3000"
    networks:
      - vth_network
    depends_on:
      vth_strapi:
        condition: service_started
      vth_strapi_db:
        condition: service_healthy
    command: ./bin/wait-for-it.sh vth_strapi:1337 -t 30 -- pnpm --filter @frameless/vth-frontend dev

  vth_strapi_db:
    container_name: vth_strapi_db
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - vth-strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - vth_network

  vth_pgadmin:
    container_name: vth_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - vth_network
    depends_on:
      - vth_strapi_db

volumes:
  vth-strapi-data:

networks:
  vth_network:
    driver: bridge
