export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const GET_SEARCH_RESULTS_ERROR = "GET_SEARCH_RESULTS_ERROR";

export const GET_SUGGESTED_SEARCH = "GET_SUGGESTED_SEARCH";
export const GET_SUGGESTED_SEARCH_ERROR = "GET_SUGGESTED_SEARCH_ERROR";