/* eslint-disable prettier/prettier */
const { config } = require('dotenv');
const path = require('path');
const cwd = path.resolve(process.cwd());
config();
// eslint-disable-next-line no-undef
module.exports = {
  apps: [
    {
      name: 'kb',
      cwd,
      script: './server.js',
      args: 'start',
      exec_mode: 'cluster',
      watch: true,
      env: {
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET_KB,
        API_TOKEN_SALT: process.env.API_TOKEN_SALT_KB,
        APP_KEYS: process.env.APP_KEYS_KB,
        DATABASE_CLIENT: process.env.DATABASE_CLIENT_KB,
        DATABASE_HOST: process.env.DATABASE_HOST_KB,
        DATABASE_NAME: process.env.DATABASE_NAME_KB,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD_KB,
        DATABASE_PORT: process.env.DATABASE_PORT_KB,
        DATABASE_SSL: process.env.DATABASE_SSL_KB,
        DATABASE_USERNAME: process.env.DATABASE_USERNAME_KB,
        FRONTEND_PUBLIC_URL: process.env.FRONTEND_PUBLIC_URL_KB,
        PORT: process.env.PORT_KB,
        HOTS: process.env.HOTS_KB,
        JWT_SECRET: process.env.JWT_SECRET_KB,
        PGADMIN_DEFAULT_EMAIL: process.env.PGADMIN_DEFAULT_EMAIL_KB,
        PGADMIN_DEFAULT_PASSWORD: process.env.PGADMIN_DEFAULT_PASSWORD_KB,
        NODE_ENV: process.env.NODE_ENV_KB,
        PREVIEW_SECRET_TOKEN: process.env.PREVIEW_SECRET_TOKEN_KB,
        STRAPI_ADMIN_NAME: process.env.STRAPI_ADMIN_NAME_KB,
        STRAPI_PRIVATE_URL: process.env.STRAPI_PRIVATE_URL_KB,
        STRAPI_PUBLIC_URL: process.env.STRAPI_PUBLIC_URL_KB,
        TRANSFER_TOKEN_SALT: process.env.TRANSFER_TOKEN_SALT_KB,
      },
    },
    {
      name: 'pdc',
      cwd,
      script: './server.js',
      exec_mode: 'cluster',
      args: 'start',
      watch: true,
      env: {
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET_PDC,
        API_TOKEN_SALT: process.env.API_TOKEN_SALT_PDC,
        APP_KEYS: process.env.APP_KEYS_PDC,
        DATABASE_CLIENT: process.env.DATABASE_CLIENT_PDC,
        DATABASE_HOST: process.env.DATABASE_HOST_PDC,
        DATABASE_NAME: process.env.DATABASE_NAME_PDC,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD_PDC,
        DATABASE_PORT: process.env.DATABASE_PORT_PDC,
        DATABASE_SSL: process.env.DATABASE_SSL_PDC,
        DATABASE_USERNAME: process.env.DATABASE_USERNAME_PDC,
        FRONTEND_PUBLIC_URL: process.env.FRONTEND_PUBLIC_URL_PDC,
        PGADMIN_DEFAULT_EMAIL: process.env.PGADMIN_DEFAULT_EMAIL_PDC,
        PGADMIN_DEFAULT_PASSWORD: process.env.PGADMIN_DEFAULT_PASSWORD_PDC,
        PORT: process.env.PORT_PDC,
        HOST: process.env.HOST_PDC,
        JWT_SECRET: process.env.JWT_SECRET_PDC,
        NODE_ENV: process.env.NODE_ENV_PDC,
        PREVIEW_SECRET_TOKEN: process.env.PREVIEW_SECRET_TOKEN_PDC,
        STRAPI_ADMIN_NAME: process.env.STRAPI_ADMIN_NAME_PDC,
        STRAPI_PRIVATE_URL: process.env.STRAPI_PRIVATE_URL_PDC,
        STRAPI_PUBLIC_URL: process.env.STRAPI_PUBLIC_URL_PDC,
        TRANSFER_TOKEN_SALT: process.env.TRANSFER_TOKEN_SALT_PDC,
      },
    },
    {
      name: 'vth',
      cwd,
      script: './server.js',
      exec_mode: 'cluster',
      args: 'start',
      watch: true,
      env: {
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET_VTH,
        API_TOKEN_SALT: process.env.API_TOKEN_SALT_VTH,
        APP_KEYS: process.env.APP_KEYS_VTH,
        DATABASE_CLIENT: process.env.DATABASE_CLIENT_VTH,
        DATABASE_HOST: process.env.DATABASE_HOST_VTH,
        DATABASE_NAME: process.env.DATABASE_NAME_VTH,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD_VTH,
        DATABASE_PORT: process.env.DATABASE_PORT_VTH,
        DATABASE_SSL: process.env.DATABASE_SSL_VTH,
        DATABASE_USERNAME: process.env.DATABASE_USERNAME_VTH,
        FRONTEND_PUBLIC_URL: process.env.FRONTEND_PUBLIC_URL_VTH,
        HOST: process.env.HOST_VTH,
        PORT: process.env.PORT_VTH,
        JWT_SECRET: process.env.JWT_SECRET_VTH,
        PGADMIN_DEFAULT_EMAIL: process.env.PGADMIN_DEFAULT_EMAIL_VTH,
        PGADMIN_DEFAULT_PASSWORD: process.env.PGADMIN_DEFAULT_PASSWORD_VTH,
        NODE_ENV: process.env.NODE_ENV_VTH,
        PREVIEW_SECRET_TOKEN: process.env.PREVIEW_SECRET_TOKEN_VTH,
        STRAPI_ADMIN_NAME: process.env.STRAPI_ADMIN_NAME_VTH,
        STRAPI_PRIVATE_URL: process.env.STRAPI_PRIVATE_URL_VTH,
        STRAPI_PUBLIC_URL: process.env.STRAPI_PUBLIC_URL_VTH,
        TRANSFER_TOKEN_SALT: process.env.TRANSFER_TOKEN_SALT_VTH,
      },
    },
  ],
};
