openapi: "3.0.0"
info:
  title: Kennisbank API
  description: API to manage Kennisbank resources
  version: 1.0.0
servers:
  - url: http://localhost:4001/api/v1
    description: Example server

paths:
  /objects:
    get:
      summary: List all objects (Kennisartikelen and VAC) or filter by type
      operationId: getObjects
      parameters:
        - in: query
          name: type
          required: false # Make 'type' optional
          schema:
            type: string
            format: uri
            enum:
              - "http://localhost:4001/api/v1/objecttypes/kennisartikel"
              - "http://localhost:4001/api/v1/objecttypes/vac"
            description: Optional parameter to filter by object type. If not specified, both types will be returned.
      responses:
        "200":
          description: A list of objects (Kennisartikelen and/or VAC)
          content:
            application/json:
              schema:
                oneOf: # Use oneOf to allow either kennisartikel or vac
                  - type: array
                    items:
                      $ref: "./kennisartikel.json"
                  - type: array
                    items:
                      $ref: "./vac.json"
                  - type: array
                    items:
                      type: object
                      additionalProperties: false
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          oneOf:
                            - $ref: "./kennisartikel.json"
                            - $ref: "./vac.json"
              example:
                results:
                  - url: "http://localhost:4001/api/v1/objecttypes/kennisartikel"
                    uuid: "123e4567-e89b-12d3-a456-426614174000"
                    upnUri: "http://example.com/upn/1"
                    publicatieDatum: "2023-01-01"
                    productAanwezig: true
                    verantwoordelijkeOrganisatie:
                      url: "http://example.com/organisatie/1"
                      owmsIdentifier: "http://example.com/owms/1"
                      owmsEndDate: "2024-01-01T00:00:00Z"
                    locaties: ["Locatie 1", "Locatie 2"]
                    doelgroep: "eu-burger"
                    afdelingen:
                      - afdelingId: "1"
                        afdelingNaam: "Burgerzaken"
                    vertalingen:
                      - taal: "nl"
                        titel: "Kennisartikel Titel"
                        tekst: "Dit is de inleiding van het kennisartikel."
                        datumWijziging: "2023-02-01T00:00:00Z"
                      - vraag: "Wat is het proces om een paspoort aan te vragen?"
                        status: "actief"
                        antwoord: "U moet een afspraak maken bij de gemeente, uw identiteitsbewijs meenemen en een recente pasfoto aanleveren."
                        doelgroep: "eu-burger"
                        afdelingen:
                          - afdelingId: "1"
                            afdelingNaam: "Burgerzaken"
                        toelichting: "Deze VAC biedt informatie over het aanvragen van een paspoort in Nederland."
                        trefwoorden:
                          - trefwoord: "paspoort"
                          - trefwoord: "aanvragen"
                        gerelateerdeVACs: []
                        gerelateerdeProducten: []
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
  /objects/{uuid}:
    get:
      summary: Get a specific object by ID
      operationId: getObjectById
      parameters:
        - in: path
          name: uuid
          required: true
          description: The unique identifier of the object
          schema:
            type: string
      responses:
        "200":
          description: Object found
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "./kennisartikel.json"
                  - $ref: "./vac.json"
              example:
                url: "http://localhost:4001/api/v1/objecttypes/vac"
                vraag: "Wat is het proces om een paspoort aan te vragen?"
                status: "actief"
                antwoord: "U moet een afspraak maken bij de gemeente, uw identiteitsbewijs meenemen en een recente pasfoto aanleveren."
                doelgroep: "eu-burger"
                afdelingen:
                  - afdelingId: "1"
                    afdelingNaam: "Burgerzaken"
                toelichting: "Deze VAC biedt informatie over het aanvragen van een paspoort in Nederland."
                trefwoorden:
                  - trefwoord: "paspoort"
                  - trefwoord: "aanvragen"
                gerelateerdeVACs: []
                gerelateerdeProducten: []
        "404":
          description: Object not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Object not found"
components:
  schemas:
    kennisartikel:
      $ref: "./kennisartikel.json"
    vac:
      $ref: "./vac.json"
