name: Release

on:
  push:
    branches: [main, beta]
  pull_request:
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@frameless"
      - run: npm ci
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_HOSTNAME: ${{ secrets.HOSTNAME }}
          envkey_API_URL_STRAPI: ${{ secrets.API_URL_STRAPI }}
          directory: apps/frontend
          file_name: .env.production.local
          fail_on_empty: false
      - name: Build
        run: npm run build
      - name: Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken=${GH_TOKEN}"
          npm run release
          npm config delete "//npm.pkg.github.com/:_authToken"
